### ISSUE TITLE
[BUG] Navigation sur une url avec des paramètres

### ISSUE THREAD

**Issue by GreenDjango** [p3ol/react-example#261]
Bonjour,

L'utilisation de `poool/react-access` fonctionne bien avec un exemple très simple comportant un composant pour une page.

Cependant quand on utilise une route avec des paramètres (ex: `<Route path="/premium/:id" element={<Premium />} />`),
le composent `Premium` n'est pas re rendu entièrement quand on passe de "/premium/1" à "/premium/2".

Cela provoque un non rafraichissement du composent poool qui n'envoie pas un nouveau `page-view` et s'active en bas de page (cf: photo).

https://github.com/GreenDjango/react-example/tree/page-with-params

Version utilisée: 
- @poool/react-access@1.2.0
- react@17.0.2
- react-dom@17.0.2

![Screenshot 2022-03-29 at 19-48-48 Poool SDK React Example](https://user-images.githubusercontent.com/52924057/160678480-8417bf85-cda2-44c9-a0c2-1b6488876bd9.png)

**Comment by dackmin** [comment]
Hello @GreenDjango,

Merci pour ton issue. C'est un comportement attendu de React qui évite que l'entièreté de la page soit re-rendered quand seulement un element dépendant d'une prop ou d'un hook a changé (ici c'est seulement ton titre qui change).
Pour éviter ça et forcer le re-render complet de la page, tu peux ajouter une prop `key={postId}` à ta div principale qui préviendra React que tout a changé à l'intérieur et que ce n'est plus du tout le même contenu.

Je ferme l'issue, n'hésite pas à réouvrir si tu veux ajouter des choses.
Bonne journée !

Ugo
